# Generated by Django 6.0.6 on 2026-06-04 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_inicio', models.DateField()),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='ativa', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='customers.cliente')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
