# Generated by Django 6.0.6 on 2026-06-04 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_logins_30dias', models.PositiveIntegerField(default=0)),
                ('horas_assistidas_30dias', models.FloatField(default=0.0)),
                ('dias_sem_acesso', models.PositiveIntegerField(default=0)),
                ('chamados_suporte', models.PositiveIntegerField(default=0)),
                ('pagamentos_atrasados', models.PositiveIntegerField(default=0)),
                ('dispositivos_cadastrados', models.PositiveIntegerField(default=1)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='customers.cliente')),
            ],
            options={
                'verbose_name': 'Métrica de Uso',
                'verbose_name_plural': 'Métricas de Uso',
            },
        ),
        migrations.CreateModel(
            name='Predicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade_cancelamento', models.FloatField(default=0.0)),
                ('nivel_risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='baixo', max_length=5)),
                ('data_predicao', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='predicao', to='customers.cliente')),
            ],
            options={
                'verbose_name': 'Predição',
                'verbose_name_plural': 'Predições',
                'ordering': ['-probabilidade_cancelamento'],
            },
        ),
    ]
