# Generated by Django 6.0.6 on 2026-06-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modelo', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('roc_auc', models.FloatField()),
                ('matriz_confusao', models.JSONField(default=list)),
                ('importancia_variaveis', models.JSONField(default=dict)),
                ('melhor_modelo', models.BooleanField(default=False)),
                ('arquivo_modelo', models.CharField(blank=True, max_length=255)),
                ('data_treinamento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resultado de Treinamento',
                'verbose_name_plural': 'Resultados de Treinamento',
                'ordering': ['-data_treinamento'],
            },
        ),
    ]
